name: E2E Tests

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:
    inputs:
      test_production:
        description: 'Test against production URL'
        required: false
        default: false
        type: boolean
      production_url:
        description: 'Production URL to test against'
        required: false
        default: 'https://your-app.vercel.app'
        type: string

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install system dependencies for Playwright
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libnspr4 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdrm2 \
          libdbus-1-3 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxrandr2 \
          libgbm1 \
          libpango-1.0-0 \
          libcairo2 \
          libasound2
    
    - name: Install Playwright Browsers
      run: npx playwright install chromium
    
    - name: Start Firebase Emulators
      run: npm run emulators &
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    
    - name: Wait for emulators to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:4000; do sleep 2; done'
    
    - name: Start React app
      run: npm run start:frontend &
      env:
        CI: true
        REACT_APP_FIREBASE_USE_EMULATORS: true
        BROWSER: none
    
    - name: Wait for React app to be ready
      run: |
        timeout 120 bash -c 'until curl -f http://localhost:3000 | grep -q "root"; do sleep 2; done'
        sleep 5
    
    - name: Debug - Check if app is running
      run: |
        echo "Checking if React app is running..."
        curl -v http://localhost:3000 || true
        echo "Checking if emulators are running..."
        curl -v http://localhost:4000 || true
        echo "Checking running processes..."
        ps aux | grep -E 'node|react-scripts|firebase' || true
    
    - name: Run E2E tests (Local)
      if: ${{ github.event.inputs.test_production != 'true' }}
      run: npm run test:e2e
      env:
        CI: true
        PLAYWRIGHT_BASE_URL: http://localhost:3000
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 1
