name: E2E Tests

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:
    inputs:
      test_production:
        description: 'Test against production URL'
        required: false
        default: false
        type: boolean
      production_url:
        description: 'Production URL to test against'
        required: false
        default: 'https://your-app.vercel.app'
        type: string

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npm run test:e2e:install
    
    - name: Start Firebase Emulators
      run: npm run emulators &
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    
    - name: Wait for emulators to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:4000; do sleep 2; done'
    
    - name: Start React app
      run: npm run start:frontend &
      env:
        CI: true
    
    - name: Wait for React app to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'
    
    - name: Run E2E tests (Local)
      if: ${{ github.event.inputs.test_production != 'true' }}
      run: npm run test:e2e
      env:
        CI: true
        PLAYWRIGHT_BASE_URL: http://localhost:3000
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 1
